---
title: "Midterm Exam"
author: "Charles Jason Tinant"
date: "3/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Orientation  
Hydrology is the study or knowledge of water.  Understanding our societal need of water is important because at every point in time there are places in the world that experience excesses or deficits of water that have an adverse impact on society and ecosystems.  Two growing areas of concern are an increasing human population that is stressing water resources, and global warming that is having an increasing impact on global food and water supplies. 

The midterm exam will evaluate your understanding of the student learning outcomes (SLOs) listed below by an open open book/note exam, followed by closed book portion during the class following spring break.

##NSci 253 Hydrology - Student Learning Outcomes (SLOs)
**SLO1: Students will demonstrate proficiency in describing and relating the components of the hydrologic cycle: precipitation, infiltration, runoff, and evapotranspiration**  

- Students will be able to generally describe the hydrologic cycle: precipitation, infiltration, evapotranspiration, runoff, and groundwater (in English and Lakota);  

- Students will be able to relate the hydrologic cycle, water resources and society using vocabulary: sustainability, water distribution, water use, water consumption, hydrologic storages: atmosphere, soil vadose zone, aquifers, lakes, streams, ocean and ice, hydrologic process: evaporation, precipitation, transpiration, infiltration, runoff, percolation, and stream flow, weather, climate, frontal precipitation, convection, orographic, stratosphere, troposphere, jet stream.  

- Students will be able to relate the hydrologic cycle, water resources and society to the local climate.  

- Students will be able perform basic hydrologic data analysis by hand and demonstrate an understanding of hydrologic graphs.

**SLO2: Students are able to analyze components of the hydrologic with computer software**  

- Students demonstrate basic proficiency in the R statistical programming language by reading 'Tidyverse' code, reading data into R, and joining data tables.  

- Students demonstrate basic manipulation tasks such as finding summaries, performing unit conversions, calculating an effective precipitation depth, precipitation volume.

## Please complete the problems below and turn them in as an Rmd file by email before class next Tuesday.

### Problem 1: Summarizing annual precipitation in west-central South Dakota
- Please use code from the lesson plans to load necessary packages, load in and transform the data from daily to annual precipitation totals in order to answer questions 1a to 1d.  
a. (7-pts) Use the Cottonwood precipitation data "1228041_cottonwood_sta.csv" to find the annual precipitation mean, median, max, min, 25%, and 75%. 
b. (3-pts) About how much precipitation should you expect for a given year?
c. (2-pts) Why is the mean different from the median annual precipitation at Cottonwood?
d. (2-pts) Was 1997 a wet year or a dry year?

- Use the daily precipitation totals to answer the following questions:
e. (2-pts)  what months had the largest rainfall events?
f. (3-pts) What kind of storms most likely produced the largest rainfall events?

### Problem 2: Precipitation depth, precipitation volume, and effective precipitation

- Acre-ft (the depth of water measured in feet on an acre of land) is the official water use measurement for the United States.  Evaporation in this part of the world is about 60% of the total depth of a given storm.

The five largest 24-hour storm depths in the Cottonwood period of record are (in inches) 5.84, 4.81, 4.00, 3.71, and 3.61.  Use these storm depths over a 100 square mile watershed to calculate the following:  

a. (3-pts) Storm depths in feet.  
b. (3-pts) Watershed area in acres.  
c. (3-pts) Total storm volume in acre-feet.  
d. (3-pts) Effective volume of the storm in acre-feet.  
e. (4-pts) Evaporation volume in cubic feet.  
f. (4-pts) If the storms fell as snow of 10% moisture content, what would be the snow depths in inches?  
\newpage 


